version: '3'

services:
  web:
    build: .
    command: python manage.py runserver
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: db.sqlite3